// src/views/WorkExperience.vue
<template>
	<section class="mb-8">
		<HeadingPrimary :text="$t('workExperience.title')"></HeadingPrimary>
		<div class="md:grid md:grid-cols-2 gap-4 space-y-4 md:space-y-0">
			<div v-for="item in data?.[$i18n.locale]" :key="item.id">
				<div
					class="relative bg-primary-600 px-4 pt-8 pb-12 rounded-t-lg text-center"
				>
					<h2 class="text-white uppercase lg:text-lg">{{ item.name }}</h2>
					<p class="text-sm text-white">
						{{ item.dateStart }} - {{ item.dateEnd }}
					</p>
					<div
						class="company-logo rounded-full h-12 w-12 bg-white flex items-center justify-center"
					>
						<img
							:src="`/assets/img/${item.logo}`"
							class="rounded-full"
							alt=""
						/>
					</div>
				</div>
				<div class="shadow rounded-b-lg px-4 py-8">
					<p class="mb-8">{{ item.description }}</p>
					<div>
						<div class="text-center">
							<button
								class="hover:bg-gray-100 w-8 h-8 rounded rounded-full p-2"
								:class="{
									'arrow-wrapper--rotate-180': showCompanies.includes(item.id),
								}"
								@click="toggleShowCompany(item.id)"
								:aria-expanded="showCompanies.includes(item.id)"
								:aria-label="`Open work experience details in ${item.name}`"
							>
								<ArrowIcon isAnimate />
							</button>
						</div>
						<div v-if="showCompanies.includes(item.id)" class="mt-4">
							<div
								v-for="(project, projectIndex) in item.projects"
								:key="`project-${project.id}`"
								:class="
									projectIndex < item.projects.length - 1
										? 'border-b border-gray-200 py-4'
										: 'pt-4'
								"
							>
								<p class="font-bold mb-2">{{ project.title }}</p>
								<div class="flex space-x-2 mb-2">
									<ion-icon
										name="people-outline"
										class="text-2xl text-gray-500"
									></ion-icon>
									<div>
										<p class="text-gray-500">{{ project.role }}</p>
										<div class="flex flex-col md:flex-row">
											<p class="text-sm text-gray-500 mb-2">
												{{ project.duration }}
											</p>
											<p class="mx-2 hidden md:block">•</p>
											<p class="text-sm text-gray-500 mb-2">
												{{ project.location }}
											</p>
										</div>
									</div>
								</div>
								<p class="mb-2">{{ project.description }}</p>
								<div class="flex flex-wrap">
									<div
										v-for="(skill, skillIndex) in project.skills"
										class="text-xs text-gray-500"
										:key="`project-${project.id}-skill-${skillIndex}`"
									>
										<span>{{ skill }}</span>
										<span
											v-if="skillIndex < project.skills.length - 1"
											class="mx-1"
											>•</span
										>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import HeadingPrimary from '../components/HeadingPrimary.vue';
import ArrowIcon from '../components/ArrowIcon.vue';
import data from '../assets/data/workExperience';
import { WorkExperience } from '../models/workExperience.model';

export default defineComponent({
	name: 'WorkExperience',
	setup: () => {
		const showCompanies = ref([] as string[]);

		function toggleShowCompany(idToRemove: string) {
			const currentIndex = showCompanies.value.findIndex(
				(item) => item === idToRemove
			);
			if (currentIndex >= 0) {
				showCompanies.value.splice(currentIndex, 1);
			} else {
				showCompanies.value.push(idToRemove);
			}
		}

		return {
			showCompanies,
			toggleShowCompany,
			data: data as unknown as {
				[key: string]: WorkExperience[];
			},
		};
	},
	components: {
		HeadingPrimary,
		ArrowIcon,
	},
});
</script>

<style lang="scss" scoped>
.company-logo {
	position: absolute;
	left: 50%;
	transform: translate(-50%, 50%);
	padding: 5px;
}
</style>

// packages/client/components/WorkExperience.tsx
import React from 'react';
import Image from 'next/image';
import Title from './Title';
import { Experience } from '../types/experience';
import { formatDate } from '../utils/date';
import { Translations } from '../types/common';

interface WorkExperienceProps {
	workExperiences: Experience[];
	translations: Translations;
}

const WorkExperience: React.FC<WorkExperienceProps> = ({
	workExperiences,
	translations,
}) => {
	const getDuration = (startDate: string, endDate: string | null): string => {
		// Get the days between two dates
		const start = new Date(startDate);
		const end = endDate === null ? new Date() : new Date(endDate);
		const diff = Math.abs(end.getTime() - start.getTime());
		const days = Math.ceil(diff / (1000 * 60 * 60 * 24));
		// Get the months between two dates
		const months = Math.floor(days / 30);
		// Get the years and months
		const years = Math.floor(months / 12);
		const remainingMonths = months % 12;
		// Create the duration string
		let duration = '';
		if (years > 0) {
			duration += `${years} ${
				years > 1
					? (translations.date.years as string)
					: (translations.date.year as string)
			}`;
		}
		if (years > 0 && remainingMonths > 0) {
			duration += ` ${translations.date.join as string} `;
		}
		if (remainingMonths > 0) {
			duration += `${remainingMonths} ${
				remainingMonths > 1
					? (translations.date.months as string)
					: (translations.date.month as string)
			}`;
		}
		return duration;
	};

	return (
		<section className="mb-8">
			<Title text={translations.workExperience.title} />
			{workExperiences.map((workExperience) => (
				<div className="card my-4" key={workExperience.id}>
					{workExperience.company !== null && (
						<div className="flex md:space-x-4 border-b-2 border-gray-200 md:border-0">
							<div className="circle hidden md:flex">
								<Image
									src={`/assets/img/${workExperience.company.logo}`}
									className="rounded-full"
									alt=""
									width={200}
									height={200}
								/>
							</div>
							<div>
								<h2 className="font-bold lg:text-lg">
									{workExperience.company.name}
								</h2>
								<p className="text-meta">
									{formatDate(workExperience.period.startDate)} -{' '}
									{workExperience.period.endDate === null
										? (translations.date.now as string)
										: formatDate(workExperience.period.endDate)}
								</p>
							</div>
						</div>
					)}
					<div>
						{workExperience.projects.map((project, projectIndex) => (
							<div
								key={project.id}
								className={
									projectIndex < workExperience.projects.length - 1
										? 'border-b border-gray-200 py-4'
										: 'pt-4'
								}
							>
								<p className="font-bold">{project.name}</p>
								<div className="flex space-x-2">
									<div>
										<p className="text-description">{project.role}</p>
										<div className="flex flex-col md:flex-row">
											<p className="text-meta mb-2">
												{getDuration(
													project.period.startDate,
													project.period.endDate
												)}
											</p>
											<p className="text-meta mx-2 hidden md:block" aria-hidden>
												•
											</p>
											<p className="text-meta mb-2">{project.location}</p>
										</div>
									</div>
								</div>
								<ul className="mb-2">
									{project.description.details?.map(
										(achievement, achievementIndex) => (
											<li key={`achievement-${achievementIndex}`}>
												<span className="ml-1">- {achievement}</span>
											</li>
										)
									)}
								</ul>
								<div className="flex flex-wrap">
									{project.skills?.map((skill, skillIndex) => (
										<div
											className="text-meta"
											key={`project-${project.id}-skill-${skillIndex}`}
										>
											<span>{skill.name}</span>
											{skillIndex < project.skills.length - 1 && (
												<span className="mx-1" aria-hidden>
													•
												</span>
											)}
										</div>
									))}
								</div>
							</div>
						))}
					</div>
				</div>
			))}
		</section>
	);
};

export default WorkExperience;
