// src/views/Courses.vue
<template>
	<section>
		<HeadingPrimary :text="$t('courses.title')"></HeadingPrimary>
		<div
			class="flex space-x-4 lg:space-x-8 bg-white rounded shadow p-4 mb-4"
			v-for="item in data?.[$i18n.locale]"
			:key="item.id"
		>
			<div
				class="rounded-full h-8 lg:h-12 w-8 lg:w-12 bg-primary-500 flex items-center my-auto"
				aria-hidden="true"
			>
				<ion-icon :name="item.icon" class="mx-auto"></ion-icon>
			</div>
			<div>
				<p>{{ item.title }}</p>
				<p class="text-xs text-gray-500">{{ item.date }}</p>
				<p class="text-sm text-gray-500">{{ item.description }}</p>
			</div>
		</div>
	</section>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import HeadingPrimary from '../components/HeadingPrimary.vue';
import data from '../assets/data/courses';
import { Course } from '../models/course.model';

export default defineComponent({
	name: 'Courses',
	components: {
		HeadingPrimary,
	},
	setup() {
		return {
			data: data as unknown as {
				[key: string]: Course[];
			},
		};
	},
});
</script>

<style lang="scss" scoped>
.course-logo {
	position: absolute;
	left: 50%;
	transform: translate(-50%, 50%);
	padding: 5px;
}
ion-icon {
	@apply text-white lg:text-2xl;
}
</style>

// components/Courses.tsx
import { useRouter } from 'next/router';
import { useMemo } from 'react';
import { Lang } from '../types/common';
import { CourseItem, LocalizedCourse } from '../types/course';
import Title from './Title';

type CoursesProp = {
	courses: LocalizedCourse;
};

const Courses = ({ courses }: CoursesProp) => {
	const { locale } = useRouter();

	const currentLocale: Lang = useMemo(() => locale as Lang, [locale]);

	return (
		<section>
			<Title text={courses[currentLocale]?.title} />
			<div className="grid grid-cols-1 gap-4">
				{courses[currentLocale]?.items?.map((item: CourseItem) => (
					<div className="card flex space-x-4 lg:space-x-8" key={item.id}>
						<div className="circle" aria-hidden="true">
							<ion-icon name={item.icon}></ion-icon>
						</div>
						<div>
							<p className="text-label">{item.title}</p>
							<p className="text-meta">{item.date}</p>
							<p className="text-description">{item.description}</p>
						</div>
					</div>
				))}
			</div>
		</section>
	);
};

export default Courses;
