// packages/@elenaorfe-client/components/Languages.tsx
import React from 'react';
import { Language } from '../types/languages';
import Title from './Title';
import { Translations } from '../types/common';

interface LanguagesProps {
	languages: Language[];
	translations: Translations;
}

const Languages: React.FC<LanguagesProps> = ({ languages, translations }) => {
	return (
		<section>
			<Title text={translations.language.title} />
			<div className="mb-8 gap-4 space-y-4 lg:grid lg:grid-cols-3 lg:space-y-0">
				{languages.map((language) => (
					<div className="card" key={language.id}>
						<p className="text-label">{language.name}</p>
						<p className="text-description">{language.proficiency}</p>
					</div>
				))}
			</div>
		</section>
	);
};

export default Languages;

// src/views/Languages.vue
<template>
  <section>
    <Title :text="$t('languages.title')"></Title>
    <div class="lg:grid lg:grid-cols-3 space-y-4 lg:space-y-0 gap-4">
      <div class="bg-white rounded shadow p-4"
           v-for="item in data?.[$i18n.locale]"
           :key="item.id">
        <p>{{ item.name }}</p>
        <p class="text-sm text-gray-500">{{ item.level }}</p>
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import Title from '../components/Title.vue'
import data from '../assets/data/languages'
import {Language} from '../models/language.model'

export default defineComponent({
  name: 'Languages',
  components: {
    Title
  },
  setup() {
    return {
      data: data as unknown as {
        [key: string]: Language[]
      }
    }
  }
})
</script>
