// apps/web/components/Portfolio/Languages.tsx
import React from 'react';
import { Translations } from '../../types/common';
import { Language } from '../../types/languages';
import Title from '../Title';

type LanguagesProps = {
	languages: Language[];
	translations: Translations;
};

const Languages = (props: LanguagesProps): React.JSX.Element => {
	const { languages, translations } = props;

	return (
		<section>
			<Title text={translations.language.title} />
			<ul className="mb-8 gap-4 space-y-4 lg:grid lg:grid-cols-3 lg:space-y-0">
				{languages.map((language) => (
					<li key={language.id} className="card p-4">
						<p className="text-base text-slate-900 dark:text-slate-100">
							{language.name}
						</p>
						<p className="text-sm text-slate-500">{language.proficiency}</p>
					</li>
				))}
			</ul>
		</section>
	);
};

export default Languages;

// src/views/Languages.vue
<template>
  <section>
    <Title :text="$t('languages.title')"></Title>
    <div class="lg:grid lg:grid-cols-3 space-y-4 lg:space-y-0 gap-4">
      <div class="bg-white rounded shadow p-4"
           v-for="item in data?.[$i18n.locale]"
           :key="item.id">
        <p>{{ item.name }}</p>
        <p class="text-sm text-gray-500">{{ item.level }}</p>
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import Title from '../components/Title.vue'
import data from '../assets/data/languages'
import {Language} from '../models/language.model'

export default defineComponent({
  name: 'Languages',
  components: {
    Title
  },
  setup() {
    return {
      data: data as unknown as {
        [key: string]: Language[]
      }
    }
  }
})
</script>
