// components/WorkExperience.tsx
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useMemo } from 'react';
import { Lang } from '../types/common';
import {
	LocalizedWorkExperience,
	WorkExperienceItem,
} from '../types/workExperience';
import Title from './Title';

type WorkExperienceProps = {
	workExperience: LocalizedWorkExperience;
};

const WorkExperience = ({ workExperience }: WorkExperienceProps) => {
	const { locale } = useRouter();
	const currentLocale: Lang = useMemo(() => locale as Lang, [locale]);

	return (
		<section className="mb-8">
			<Title text={workExperience[currentLocale]?.title} />
			{workExperience[currentLocale]?.items?.map((item: WorkExperienceItem) => (
				<div className="my-4" key={`workExperience-${item.id}`}>
					<div className="card-header">
						<h2 className="text-white uppercase lg:text-lg">{item.name}</h2>
						<p className="text-sm text-white">
							{item.dateStart} - {item.dateEnd}
						</p>
						<div className="rounded-full h-12 w-12 bg-white flex items-center justify-center mx-auto my-2">
							<Image
								src={`/assets/img/${item.logo}`}
								className="rounded-full"
								alt=""
								width={200}
								height={200}
							/>
						</div>
					</div>
					<div className="card-body">
						<p className="mb-8">{item.description}</p>
						<div className="mt-4">
							{item.projects.map((project, projectIndex) => (
								<div
									key={`project-${project.id}`}
									className={
										projectIndex < item.projects.length - 1
											? 'border-b border-gray-200 py-4'
											: 'pt-4'
									}
								>
									<p className="font-bold mb-2">{project.title}</p>
									<div className="flex space-x-2 mb-2">
										<ion-icon
											name="people-outline"
											className="text-2xl text-gray-500"
										></ion-icon>
										<div>
											<p className="text-gray-500">{project.role}</p>
											<div className="flex flex-col md:flex-row">
												<p className="text-sm text-gray-500 mb-2">
													{project.duration}
												</p>
												<p className="mx-2 hidden md:block">•</p>
												<p className="text-sm text-gray-500 mb-2">
													{project.location}
												</p>
											</div>
										</div>
									</div>
									<p className="mb-2">{project.description}</p>
									<div className="flex flex-wrap">
										{project.skills?.map((skill, skillIndex) => (
											<div
												className="text-xs text-gray-500"
												key={`project-${project.id}-skill-${skillIndex}`}
											>
												<span>{skill}</span>
												{skillIndex < project.skills.length - 1 && (
													<span className="mx-1">•</span>
												)}
											</div>
										))}
									</div>
								</div>
							))}
						</div>
					</div>
				</div>
			))}
		</section>
	);
};

export default WorkExperience;

// src/components/WorkExperience.vue
<template>
  <v-timeline class="work-experience" dense clipped align-top>
    <v-timeline-item fill-dot class="white--text" color="white" large>
      <template v-slot:icon>
        <v-avatar>
          <img :src="require(`@/assets/img/${workExperienceInternal.logo}`)" />
        </v-avatar>
      </template>
      <v-card>
        <v-card-title class="headline">
          <v-row justify="space-between">
            <v-col cols="12" sm="6"> {{ workExperienceInternal.name }}</v-col>
            <v-col cols="12" sm="6" class="text-sm-right text-subtitle-1">
              {{ workExperienceInternal.dateStart }}
              -
              {{ workExperienceInternal.dateEnd }}
            </v-col>
          </v-row>
        </v-card-title>
        <v-card-text>
          {{ workExperienceInternal.description }}
        </v-card-text>
      </v-card>
    </v-timeline-item>

    <v-slide-x-transition group>
      <v-timeline-item
        v-for="(project, index) in workExperienceInternal.projects"
        :key="index"
        class="mb-4"
        :color="workExperienceInternal.color"
        small
      >
        <v-row justify="space-between">
          <v-col cols="12" sm="8" class="py-0">
            <span class="subtitle-1 font-weight-bold">{{ project.title }}</span>
          </v-col>
          <v-col cols="12" sm="4" class="text-sm-right text-caption py-0">
            <span>{{ project.location }}</span>
            <span class="mx-1"> | </span>
            <span>{{ project.duration }}</span>
          </v-col>
        </v-row>

        <v-row justify="space-between">
          <v-col cols="12" class="pt-0">
            <span>{{ project.description }}</span>
            <ul>
              <li v-for="(task, index) in project.tasks" :key="index">
                {{ task }}
              </li>
            </ul>
            <ul class="list-horizontal">
              <li v-for="(skill, index) in project.skills" :key="index">
                {{ skill }}
              </li>
            </ul>
          </v-col>
        </v-row>
      </v-timeline-item>
    </v-slide-x-transition>
  </v-timeline>
</template>

<script>
import Vue from "vue";
import { WorkExperienceItem } from "@/models/workExperiences";

export default Vue.extend({
  name: "WorkExperience",
  props: {
    workExperience: {
      default: {}
    }
  },
  data() {
    return {
      workExperienceInternal: this.workExperience
    };
  }
});
</script>

<style lang="scss">
.v-timeline.work-experience {
  & .v-timeline-item {
    & .v-card {
      box-shadow: none;
      & .v-card__title,
      .v-card__text {
        padding: 0px;
      }
    }
    & .v-card:after,
    .v-card:before {
      border: none;
    }

    ul {
      list-style-type: none;
      padding-left: 0px;

      li:before {
        content: "-";
        padding-right: 5px;
      }
    }

    ul.list-horizontal {
      list-style-type: none;
      padding-left: 0px;

      & li {
        float: left;
        display: block;
        padding-right: 5px;

        &:before {
          content: "";
        }

        &:first-child:before {
          content: "🖥";
          margin-right: 5px;
        }

        &:not(:last-child):after {
          content: "·";
          margin-left: 5px;
        }
      }
    }
  }
}
</style>
